[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/apps.html"
  to = "/apps"
  status = 301
  force = true

[[redirects]]
  from = "/gxmes.html"
  to = "/gxmes"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/games/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"